Various fixes and cleanup.

diff --git a/clipboard-to-file b/clipboard-to-file
--- a/clipboard-to-file
+++ b/clipboard-to-file
@@ -35,6 +35,12 @@ PROGNAME="$(basename $0)"
 DEFAULT_FILENAME="readme.txt"
 
 
+msg_error()
+{
+    printf '[ERROR] %s\n' "$*" >&2
+}
+
+
 if ! command -v "xclip" >/dev/null
 then
     echo "ERROR: Unable to execute xclip. Exiting .."
@@ -49,31 +55,24 @@ then
     echo "       FILE - Optional name of the file."
     echo "              (Defaults to \"${DEFAULT_FILENAME}\")"
     exit 1
-else
-    if [ ! -d "$1" ]
-    then
-        echo "ERROR: Not a directory: \"${dest}\". Exiting .." >&2
-        exit 1
-    fi
-
-    dest="${1}/${2:-$DEFAULT_FILENAME}"
-
-    if [ -e "$dest" ]
-    then
-        echo "ERROR: ${dest} already exists and would be overwritten. Exiting .." >&2
-        exit 1
-    fi
-
-    # Have xclip output the clipboard (X selection) contents to $dest
-    xclip -out > "$dest"
-
-    # Test for zero file size, delete file if true. Could happen if the
-    # clipboard is empty or contains something unsuitable for stdout.
-    if [ ! -s "$dest" ]
-    then
-        rm -v -- "$dest"
-    fi
-
-    exit 0
 fi
 
+[ -e "$1" ] || { msg_error "Does not exist: \"${1}\" .."  ; exit 1 ; }
+[ -d "$1" ] || { msg_error "Not a directory: \"${1}\" .." ; exit 1 ; }
+
+dest="${1}/${2:-$DEFAULT_FILENAME}"
+
+[ -e "$dest" ] && { msg_error "Would be overwritten: \"${dest}\" .."     ; exit 1 ; }
+[ -w "$dest" ] || { msg_error "Missing write permission: \"${dest}\" .." ; exit 1 ; }
+
+# Have xclip output the clipboard (X selection) contents to $dest
+xclip -out > "$dest"
+
+# Test for zero file size, delete file if true. Could happen if the
+# clipboard is empty or contains something unsuitable for stdout.
+if [ ! -s "$dest" ]
+then
+    rm -v -- "$dest"
+fi
+
+exit $?
