Line up markers ..

diff --git a/clipboard-to-file b/clipboard-to-file
--- a/clipboard-to-file
+++ b/clipboard-to-file
@@ -43,10 +43,10 @@ fi
 
 if [ $# -eq 0 ]
 then
-    echo "ERROR: Positional argument is missing!" >&2
-    echo "USAGE: ${PROGNAME} [PATH] [FILE]" >&2
-    echo "       PATH - Create the file in this directory" >&2
-    echo "       FILE - Optional name of the file." >&2
+    echo "ERROR: Positional argument is missing!"              >&2
+    echo "USAGE: ${PROGNAME} [PATH] [FILE]"                    >&2
+    echo "       PATH - Create the file in this directory"     >&2
+    echo "       FILE - Optional name of the file."            >&2
     echo "              (Defaults to \"${DEFAULT_FILENAME}\")" >&2
     exit 1
 else
