Add test for required program in related scripts.

diff --git a/convert-video-to-mp4 b/convert-video-to-mp4
--- a/convert-video-to-mp4
+++ b/convert-video-to-mp4
@@ -30,6 +30,11 @@ function msg_error()
 }
 
 
+if ! command -v ffmpeg >/dev/null 2>&1; then
+    echo "Required program \"ffmpeg\" is not available. Exiting." 2>&1
+    exit 1
+fi
+
 if [ $# -eq 0 ]
 then
     printf "%-8s %s\n" "Usage:" "$(basename $0) [FILE]..."
