Rework 'fix-permissions'.

diff --git a/fix-permissions b/fix-permissions
--- a/fix-permissions
+++ b/fix-permissions
@@ -2,8 +2,7 @@
 
 # Recursively set permissions
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~
-# Recursively set permissions in shared "data" folders.
-#_______________________________________________________________________________
+# Recursively changes file and directory permissions, owner and group.
 #
 #     This program is free software: you can redistribute it and/or modify
 #     it under the terms of the GNU General Public License as published by
@@ -19,42 +18,64 @@
 #    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #_______________________________________________________________________________
 
-set -e                          # exit on first error
-#set -x                         # debug mode
-
-                                #                      owner   group   other
-DIR_PERMS='775'                 # directories    775   r w x   r w x   r   x
-FILE_PERMS='664'                # files          664   r w     r w     r
+# User configurable options:
+                                #                    Owner   Group   Other
+CHMOD_DIRS='775'                # DIRECTORIES (775)  R W X   R W X   R   X
+CHMOD_FILE='664'                #       FILES (664)  R W     R W     R
+CHOWN_USER="$(whoami)"
+CHOWN_GROUP="$(whoami)"
 
 #_______________________________________________________________________________
 
+#set -e                         # exit on first error
+#set -x                         # debug mode
 
-path=${1%/}
-USE_USER="spock"
+function msg_error()
+{
+    printf "[ERROR] %s\n" "$*" >&2
+}
 
-if [[ ${path} && ${path-x} ]];
+function msg_argerr()
+{
+    msg_error "${1}: \"${2}\""
+}
+
+function msg_usage()
+{
+    printf "\nUSAGE: $(basename "$0") [PATH]\n"
+    printf "\nModifies owner, group and permissions for PATH recursively using options:\n"
+    FMT="  %-30.30s: %s\n"
+    printf "$FMT" "chown (owner, group)"       "[${CHOWN_USER}] [${CHOWN_GROUP}]"
+    printf "$FMT" "chmod (directories, files)" "[${CHMOD_DIRS}] [${CHMOD_FILE}]"
+    printf "\nNote that this script should be executed with elevated privileges.\n"
+}
+
+if [ $# -eq 0 ]
 then
-    if [[ ! -d $path ]]; then
-        echo "starting directory path does not exist or isn't a directory!"
-        exit 1
-    fi
-
-    echo "confirm starting path: \"$path\" .."
-    read -rsp $'Press any key to continue...\n' -n 1 key
-
-    echo "changing owner .."
-    chown -R ${USE_USER}:${USE_USER} "${path}"
-
-    echo "chmodding directories .."
-    find "${path}" -type d -exec chmod $DIR_PERMS '{}' \;
-
-    echo "chmodding files .."
-    find "${path}" -type f -exec chmod $FILE_PERMS '{}' \;
-
-    echo ".. done!"
-    exit $?
-else
-    echo "path argument required!" 
-    echo "USAGE: $0 /starting/directory/path"
+    msg_usage
     exit 1
 fi
+
+path="${1%/}"
+[ -z "$path" ] && { msg_argerr "Got null argument" "$path" ; exit 1 ; }
+[ -e "$path" ] || { msg_argerr "Does not exist"    "$path" ; exit 1 ; }
+[ -d "$path" ] || { msg_argerr "Not a directory"   "$path" ; exit 1 ; }
+
+printf "Using path: \"${path}\"\n"
+read -rsp $'Press any key to continue .. (ctrl-c aborts)\n' -n 1 key
+
+printf "\nChowning directories and files .."
+chown -R "${CHOWN_USER}:${CHOWN_GROUP}" "${path}"
+printf " [OK]\n"
+
+printf "Chmodding directories .. "
+find "$path" -type d -exec chmod $CHMOD_DIRS '{}' \;
+[ $? -eq 0 ] && printf "[OK]\n"
+
+printf "Chmodding files .. "
+find "$path" -type f -exec chmod $CHMOD_FILE '{}' \;
+[ $? -eq 0 ] && printf "[OK]\n"
+
+[ -n ${SECONDS} ] && printf "\nTotal execution time: ${SECONDS} seconds\n"
+
+exit $?
