Fix error message spelling.

diff --git a/folder-manifest b/folder-manifest
--- a/folder-manifest
+++ b/folder-manifest
@@ -82,7 +82,7 @@ if [[ -d "$@" ]]; then
         exit 0
     else
         # Display error and die.
-        echo "Error! Need write permissions to "${THIS_WORKING_PATH}"!" >&2
+        echo "Error! Need write permissions for "${THIS_WORKING_PATH}"!" >&2
         exit 1
     fi
 else
