Add handling multiple arguments.
* Move main routine to a function.
* Call new main function with each argument in turn.

diff --git a/slugify-filename b/slugify-filename
--- a/slugify-filename
+++ b/slugify-filename
@@ -152,88 +152,114 @@ process_second_run()
         msg_debug
     done
 
-    
+    #if [[ $NAME =~ [$[0-9]{4}-[0-9]{2}-[0-9]{2}-[0-9]{2}-[0-9]{2}-[0-9]{2}] ]]
+    #then
+    # TODO: Check for date-like patterns (2015-01-01-11-11-11) and rename appropriately.
+    #fi
+
     echo "${name}" # Function "return" value
+}
+
+main()
+{
+    name_full="${1}"
+    name_no_path="${name_full##*/}"
+    extension="${name_full##*.}"
+    name_no_ext=${name_full%.*}
+
+    msg_progress "name_full:      $name_full"
+    msg_progress "name_no_path:   $name_no_path"
+    msg_progress "extension:      $extension"
+    msg_progress "name_no_ext:    $name_no_ext"
+
+    if [[ ! -z ${extension} ]]
+    then
+        msg_prompt "slugifying extension"
+        extension="$(process "${extension}")"
+        msg_progress "extension:      $extension"
+    fi
+
+    if [[ ! -z ${name_no_ext} ]]
+    then
+        msg_prompt "slugifying name_no_ext"
+        name_no_ext="$(process "${name_no_ext}")"
+        msg_progress "name_no_ext:    $name_no_ext"
+    fi
+
+    if [[ -z ${name_no_ext} ]]
+    then
+        msg_prompt "name without extension is EMPTY! setting to .extension"
+        name_no_ext=".${extension}"
+        extension=''
+        msg_progress "extension:      $extension"
+        msg_progress "name_no_ext:    $name_no_ext"
+    fi
+
+
+    if [[ ! -z ${extension} ]]
+    then
+        msg_prompt "extension is *not* NULL"
+
+        if [[ "${extension}" == "${name_no_ext}" ]]
+        then
+            msg_prompt "extension is equal to full name. Setting to NULL"
+            extension=''
+            #name_no_ext=".${name_no_ext}"
+        else
+            extension=".${extension}"
+            msg_progress "extension:      $extension"
+        fi
+    fi
+
+
+    name_new="${name_no_ext}"
+    msg_progress "name_new:       $name_new"
+
+    msg_prompt "start second run process"
+    name_new="$(process_second_run "${name_new}")"
+    msg_progress "name_new:       $name_new"
+
+    if [[ -z ${name_new} ]]
+    then
+        msg_debug "process result is NULL!"
+        return
+    fi
+
+
+    name_new_full="${name_new}${extension}"
+    msg_progress "name_new_full:  $name_new_full"
+
+    if [[ "${name_full}" != "${name_new_full}" ]]
+    then
+        msg_prompt "DONE! Result is not equal to input"
+    else
+        msg_prompt "DONE! nothing changed"
+    fi
+
+
+    if [[ "$DEBUG_MODE" == true ]]
+    then
+        echo "${name_new_full}"
+        return
+    else
+        mv -n "${1}" "${name_new_full}"
+    fi
 }
 
 
 
+# ______________________________________________________________________________
 # MAIN ROUTINE EXECUTION STARTS HERE
-msg_prompt "RUNNING"
 
-name_full="${1}"
-name_no_path="${name_full##*/}"
-extension="${name_full##*.}"
-name_no_ext=${name_full%.*}
-
-msg_progress "name_full:      $name_full"
-msg_progress "name_no_path:   $name_no_path"
-msg_progress "extension:      $extension"
-msg_progress "name_no_ext:    $name_no_ext"
-
-
-if [[ ! -z ${name_no_ext} ]];
+if [ $# -eq 0 ]
 then
-    msg_prompt "slugifying name_no_ext"
-    name_no_ext="$(process "${name_no_ext}")"
-    msg_progress "name_no_ext:    $name_no_ext"
-fi
-
-if [[ -z ${name_no_ext} ]];
-then
-    msg_prompt "name without extension is EMPTY! setting to .extension"
-    name_no_ext=".${extension}"
-    extension=''
-    msg_progress "extension:      $extension"
-    msg_progress "name_no_ext:    $name_no_ext"
-fi
-
-
-if [[ ! -z ${extension} ]];
-then
-    msg_prompt "extension is *not* NULL"
-
-    if [[ "${extension}" == "${name_no_ext}" ]];
-    then
-        msg_prompt "extension is equal to full name. Setting to NULL"
-        extension=''
-        #name_no_ext=".${name_no_ext}"
-    else
-        extension=".${extension}"
-        msg_progress "extension:      $extension"
-    fi
-fi
-
-name_new="${name_no_ext}"
-msg_progress "name_new:       $name_new"
-
-msg_prompt "start second run process"
-name_new="$(process_second_run "${name_new}")"
-
-msg_progress "name_new:       $name_new"
-
-
-#if [[ -z ${extension} ]];
-#then
-    #msg_prompt "adding back leading dot"
-    #name_new=".${name_new}"
-#fi
-
-
-name_new_full="${name_new}${extension}"
-msg_progress "name_new_full:  $name_new_full"
-
-if [[ "${name_full}" != "${name_new_full}" ]];
-then
-    msg_prompt "DONE! Result is not equal to input"
+    die 1 "Positional arguments missing! At least one is required."
 else
-    msg_prompt "DONE! nothing changed"
+    for arg in "$@"
+    do
+        main "${arg}"
+    done
 fi
 
+exit $?
 
-if [[ "$DEBUG_MODE" == true ]]; then
-    echo "${name_new_full}"
-    exit 0
-else
-    mv -n "${1}" "${name_new_full}"
-fi
