Fix extension in resulting filename.
Fixed up original extension ending up in the resulting file name using
Bash builtin functionality.

diff --git a/vrml2png b/vrml2png
--- a/vrml2png
+++ b/vrml2png
@@ -22,34 +22,34 @@ echo "Generating previews of 3D-models .."
 echo ""
 
 for vrmlfile in *.wrl;
-do                                          # iterate through files
+do                                               # iterate through files
     echo "processing vrmlfile: "$vrmlfile" .."
 
     COUNTER_VRMLFILES=$[$COUNTER_VRMLFILES +1]
 
     for angle in {0..6};
-    do                                      # iterate through angles per file
-        outputfile="${vrmlfile}_${angle}".png
-
-        if [ ! -f $outputfile ];            # make sure file does not exist
-        then                                # ok the file isn't there
+    do                                           # iterate through angles per file
+        outputfile="${vrmlfile%.*}_${angle}.png" # (%.* strips file extension)
+                                                 
+        if [ ! -f $outputfile ];                 # make sure file does not exist
+        then                                     # ok the file isn't there
             echo "writing: "$outputfile" .."
             view3dscene "${vrmlfile}" --viewpoint "$angle" \
                         --screenshot 0 "${outputfile}";
 
             COUNTER_TOTALPNGS=$[$COUNTER_TOTALPNGS +1]
-        else                                # file already exists
+        else                                     # file already exists
             echo "error: "$outputfile" already exists! skipping .."
         fi
-    done                                    # angle iteration done
+    done                                         # angle iteration done
 
     echo ""
-done                                        # file iteration done
+done                                             # file iteration done
 
 
 echo "Done generating previews of 3D-models!"
 echo "Total number of vrmlfiles processed (including skipped): $COUNTER_VRMLFILES"
 echo "Total number of png images generated: $COUNTER_TOTALPNGS"
 
-exit $?                                     # exit with last process exit status
+exit $?                                          # exit with last process exit status
 
