Add labeling of images.
Adds a label to the image with a timestamp and the source url.

diff --git a/www2png b/www2png
--- a/www2png
+++ b/www2png
@@ -28,7 +28,8 @@
 # ------------------------------------------------------------------------------
 
 # Use these settings when running cutycapt:
-FLAGS="--out-format=png --javascript=off --java=off"
+EXTENSION="png"
+FLAGS="--out-format=${EXTENSION} --javascript=off --java=off"
 
 # ------------------------------------------------------------------------------
 
@@ -38,6 +39,7 @@ URL=${1}                        # The URL to capture (http:...|file:...|...)
 TARGET=${2}                     # The target file (.png|pdf|ps|svg|jpeg|...)
 
 PROGNAME=$(basename $0)         # Name of this script
+TIMESTAMP="$(date +%F\ %H:%M:%S)"
 
 
 die()
@@ -48,6 +50,7 @@ die()
     fi
     exit 1
 }
+
 
 usage()
 {
@@ -61,7 +64,7 @@ usage()
 }
 
 
-if ! command -v "cutycapt" >/dev/null; then # make sure cutycapt is available
+if ! command -v "cutycapt" >/dev/null; then
     die "Can not execute cutycapt! Is it installed? Is it in your \$PATH?"
 fi
 
@@ -96,9 +99,26 @@ then
 
     if [[ ! -e ${TARGET} ]];                # does TARGET exist?
     then
-        printf "Running cutycapt.."
-
+        printf "Running cutycapt.. "
         cutycapt ${FLAGS} --url="${URL}" --out="${TARGET}"
+
+        if [[ -e "${TARGET}" ]];
+        then
+            printf "Adding label.."
+            temp_name="${TARGET%.*}_labeled.${EXTENSION}"
+
+            convert "${TARGET}" -background White \
+            label:"${TIMESTAMP}: \'${URL}\'  .. generated by ${PROGNAME}." \
+            -gravity Center -append \
+            "$temp_name"
+        else
+            printf "Adding label FAILED!"
+        fi
+
+        if [[ -e ${temp_name} ]];
+        then
+            mv "${temp_name}" "${TARGET}"
+        fi
 
         printf " DONE!\n"
         exit 0
