Various minor fixes to 'www2png'.

diff --git a/www2png b/www2png
--- a/www2png
+++ b/www2png
@@ -4,7 +4,7 @@
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~
 # Convert html to jpg/png/pdf/.. etc., with cutycapt.
 #
-# Copyright (C) 2015-2017 Jonas Sjöberg
+# Copyright (C) 2015-2018 Jonas Sjöberg
 # https://github.com/jonasjberg
 
 # Restricts what cutycapt can do to just this one thing.
@@ -33,36 +33,35 @@ FLAGS="--out-format=${EXTENSION} --javascript=on --java=off --delay=5000"
 
 # ------------------------------------------------------------------------------
 
-set -e                          # Exit immediately if a command returns non-zero.
+set -o errexit -o noclobber -o nounset -o pipefail
 
-URL="${1}"                      # The URL to capture (http:...|file:...|...)
-TARGET="${2}"                   # The target file (.png|pdf|ps|svg|jpeg|...)
-
-PROGNAME="$(basename $0)"       # Name of this script
+URL="$1"            # The URL to capture (http:...|file:...|...)
+TARGET="${2:-}"     # The target file (.png|pdf|ps|svg|jpeg|...)
+PROGNAME="$(basename -- $0)"
 TIMESTAMP="$(date +%F\ %H:%M:%S)"
 
 
 function die()
 {
     local msg="${1:-"ABORTING because of unspecified error."}"
-    printf "%s ERROR: %s\n\n" "$PROGNAME" "$msg" 1>&2
+    printf '%s ERROR: %s\n\n' "$PROGNAME" "$msg" 1>&2
     exit ${2:-1}
 }
 
 function show_usage()
 {
-    printf "usage: %s <URL> <TARGET>\n\n" "$PROGNAME"
-    printf "       <URL>       The URL to capture (http:...|file:...|...)\n"
-    printf "       <TARGET>    The target file    (.png|pdf|ps|svg|jpeg|...)\n\n"
-    printf "       Target is optional and defaults to using whatever comes\n"
-    printf "       after the last \'/\' in the URL with '.png' appended.\n"
+    printf 'usage: %s <URL> <TARGET>\n\n' "$PROGNAME"
+    printf '       <URL>       The URL to capture (http:...|file:...|...)\n'
+    printf '       <TARGET>    The target file    (.png|pdf|ps|svg|jpeg|...)\n\n'
+    printf '       Target is optional and defaults to using whatever comes\n'
+    printf "       after the last '/' in the URL with '.png' appended.\n"
 }
 
 
 # Check for required program.
-if ! command -v "cutycapt" >/dev/null
+if ! command -v "cutycapt" &>/dev/null
 then
-    die "Can not execute \"cutycapt\", is it installed? Is it in your \$PATH?"
+    die 'Could not execute "cutycapt", is it installed? Is it in your $PATH?'
 fi
 
 if ! [[ ${URL} && ${URL-x} ]]               # is URL set?
@@ -71,60 +70,66 @@ then
     exit 2
 fi
 
-if ! [[ ${TARGET} && ${TARGET-x} ]]         # is TARGET set?
+if ! [[ ${TARGET} && ${TARGET-x} ]]
 then
     # TARGET is NOT set. Extract last part of URL
-    URL="${URL%/}"                          # Remove trailing slash if present
-    URL_tail="${URL##*/}"                   # Get everything after the last '/'
+    URL="${URL%/}"          # Remove trailing slash if present
+    URL_tail="${URL##*/}"   # Get everything after the last '/'
 
     # Remove all non-alphanumerics/underscores/dashes
-    URL_tail="$(echo "$URL_tail" | sed 's/[^a-zA-Z0-9_-]/-/g')"
+    URL_tail="$(sed 's/[^a-zA-Z0-9_-]/-/g' <<< "$URL_tail")"
 
     # Remove any leading and trailing dashes/underlines
-    URL_slugify="$(echo "$URL_tail" | sed -r 's/^[_-]+//g')"
-    URL_slugify="$(echo "$URL_slugify" | sed -r 's/[_-]+$//g')"
+    URL_slugify="$(sed -r 's/^[_-]+//g ; s/[_-]+$//g' <<< "$URL_tail")"
 
     # Replace two or more dashes with a underline, collapse underlines
-    URL_slugified="$(echo "$URL_slugify" | sed -r 's/[-]{2,}/_/g')"
-    URL_slugified="$(echo "$URL_slugify" | sed -r 's/[_]{2,}/_/g')"
+    URL_slugified="$(sed -r 's/[-]{2,}/_/g ; s/[_]{2,}/_/g' <<< "$URL_slugify")"
 
     # Update TARGET file name
     TARGET="$URL_slugified"
 fi
 
-if ! [[ $TARGET == *.${EXTENSION} ]]        # Append EXTENSION if missing.
+if ! [[ $TARGET == *.${EXTENSION} ]]
 then
+    # Append EXTENSION to destination file name.
     TARGET="${TARGET}.${EXTENSION}"
 fi
 
-if [[ -e $TARGET ]]                         # does TARGET exist?
+if [[ -e $TARGET ]]
 then
     die "Target file already exists and would be overwritten"
 fi
 
-echo "Saving \"${URL}\" to \"${TARGET}\" .."
+printf 'Saving "%s" to "%s" ..\n' "$URL" "$TARGET"
 printf "Running cutycapt.. "
-cutycapt $FLAGS --url="$URL" --out="$TARGET"
-
-if [[ -e $TARGET ]]
+if cutycapt $FLAGS --url="$URL" --out="$TARGET"
 then
-    printf "Adding label.."
+    if ! [[ -e $TARGET ]]
+    then
+        die 'cutycapt did not produce a file'
+    fi
+
     temp_name="${TARGET%.*}_labeled.${EXTENSION}"
+    label_text="Generated by $PROGNAME at $TIMESTAMP from URL \'${URL}\'"
 
-    convert "$TARGET" -background White \
-    label:"${TIMESTAMP}: \'${URL}\'  .. generated by ${PROGNAME}." \
-    -gravity Center -append \
-    "$temp_name"
+    printf "Adding label.."
+    if convert "$TARGET" \
+               -background White \
+               label:"$label_text" \
+               -gravity Center \
+               -append \
+               "$temp_name"
+    then
+        if [[ -e $temp_name ]]
+        then
+            mv -- "$temp_name" "$TARGET"
+        fi
+
+        printf " DONE!\n"
+        exit 0
+    else
+        die 'Error while running convert'
+    fi
 else
-    printf "Adding label FAILED!"
+    die 'Error while running cutycapt'
 fi
-
-if [[ -e $temp_name ]]
-then
-    mv "$temp_name" "$TARGET"
-fi
-
-printf " DONE!\n"
-exit 0
-
-
