Major rewrite ..
* Fixes overall structure. Easier to read.
* Adds check for file extension.
* Various fixes.

diff --git a/www2png b/www2png
--- a/www2png
+++ b/www2png
@@ -61,72 +61,69 @@ function show_usage()
     printf "       after the last \'/\' in the URL with '.png' appended.\n"
 }
 
-
+# Check for required program.
 if ! command -v "cutycapt" >/dev/null
 then
     die "Can not execute cutycapt! Is it installed? Is it in your \$PATH?"
 fi
 
-
-if [[ ${URL} && ${URL-x} ]]                 # is URL set?
+if ! [[ ${URL} && ${URL-x} ]]               # is URL set?
 then
-    if [[ ${TARGET} && ${TARGET-x} ]]       # is TARGET set?
-    then
-        # <TARGET> IS set.
-        echo "Saving to \"$TARGET\""
-    else
-        # <TARGET> is NOT set. Extract last part of URL and append '.png'
-        URL=${URL%/}                        # Remove trailing slash if present
-        URL_tail="$(echo ${URL##*/})"       # Get everything after the last '/'
-
-        # Remove non-alphanumeric chars
-        URL_tail_alphanumeric=$(echo $URL_tail | sed 's/[^a-zA-Z0-9_-]/-/g')
-
-        # Remove any dashes and underlines if first or last in name
-        URL_slugify=$(echo $URL_tail_alphanumeric | sed -r 's/^[_-]+//g')
-        URL_slugifying=$(echo $URL_slugify | sed -r 's/[_-]+$//g')
-
-        # Replace two or more dashes with a underline, collapse underlines
-        URL_slugified=$(echo $URL_slugifying | sed -r 's/[-]{2,}/_/g')
-        URL_slugified=$(echo $URL_slugifying | sed -r 's/[_]{2,}/_/g')
-
-        # Append file extension
-        TARGET="${URL_slugified}.png"
-
-        echo "Using default target \"$TARGET\""
-    fi
-
-    if [[ ! -e ${TARGET} ]]                 # does TARGET exist?
-    then
-        printf "Running cutycapt.. "
-        cutycapt ${FLAGS} --url="${URL}" --out="${TARGET}"
-
-        if [[ -e "${TARGET}" ]]
-        then
-            printf "Adding label.."
-            temp_name="${TARGET%.*}_labeled.${EXTENSION}"
-
-            convert "${TARGET}" -background White \
-            label:"${TIMESTAMP}: \'${URL}\'  .. generated by ${PROGNAME}." \
-            -gravity Center -append \
-            "$temp_name"
-        else
-            printf "Adding label FAILED!"
-        fi
-
-        if [[ -e ${temp_name} ]]
-        then
-            mv "${temp_name}" "${TARGET}"
-        fi
-
-        printf " DONE!\n"
-        exit 0
-    else
-        die "Output file already exists!"
-    fi
-else
-    # <URL> must be set. Display usage and exit.
     show_usage
     exit 2
 fi
+
+if ! [[ ${TARGET} && ${TARGET-x} ]]         # is TARGET set?
+then
+    # TARGET is NOT set. Extract last part of URL
+    URL=${URL%/}                            # Remove trailing slash if present
+    URL_tail="$(echo ${URL##*/})"           # Get everything after the last '/'
+
+    # Remove non-alphanumeric chars
+    URL_tail_alphanumeric=$(echo $URL_tail | sed 's/[^a-zA-Z0-9_-]/-/g')
+
+    # Remove any dashes and underlines if first or last in name
+    URL_slugify=$(echo $URL_tail_alphanumeric | sed -r 's/^[_-]+//g')
+    URL_slugifying=$(echo $URL_slugify | sed -r 's/[_-]+$//g')
+
+    # Replace two or more dashes with a underline, collapse underlines
+    URL_slugified=$(echo $URL_slugifying | sed -r 's/[-]{2,}/_/g')
+    URL_slugified=$(echo $URL_slugifying | sed -r 's/[_]{2,}/_/g')
+fi
+
+if ! [[ $TARGET == *.${EXTENSION} ]]        # Append EXTENSION if missing.
+then
+    TARGET="${TARGET}.${EXTENSION}"
+fi
+
+if [[ -e ${TARGET} ]]                       # does TARGET exist?
+then
+    die "Output file already exists!"
+fi
+
+echo "Saving to \"$TARGET\" .."
+printf "Running cutycapt.. "
+cutycapt ${FLAGS} --url="${URL}" --out="${TARGET}"
+
+if [[ -e "${TARGET}" ]]
+then
+    printf "Adding label.."
+    temp_name="${TARGET%.*}_labeled.${EXTENSION}"
+
+    convert "${TARGET}" -background White \
+    label:"${TIMESTAMP}: \'${URL}\'  .. generated by ${PROGNAME}." \
+    -gravity Center -append \
+    "$temp_name"
+else
+    printf "Adding label FAILED!"
+fi
+
+if [[ -e ${temp_name} ]]
+then
+    mv "${temp_name}" "${TARGET}"
+fi
+
+printf " DONE!\n"
+exit 0
+
 
