Bump year in header. Various fixes.

diff --git a/www2png b/www2png
--- a/www2png
+++ b/www2png
@@ -4,7 +4,7 @@
 # ~~~~~~~~~~~~~~~~~~~~~~~~~~~
 # Convert html to jpg/png/pdf/.. etc., with cutycapt.
 #
-# Copyright (C) 2015 Jonas Sjöberg
+# Copyright (C) 2015-2016 Jonas Sjöberg
 # https://github.com/jonasjberg
 
 # Restricts what cutycapt can do to just this one thing.
@@ -33,7 +33,7 @@ FLAGS="--out-format=${EXTENSION} --javascript=off --java=off"
 
 # ------------------------------------------------------------------------------
 
-set -e                         # Exit immediately if a command returns non-zero.
+set -e                          # Exit immediately if a command returns non-zero.
 
 URL=${1}                        # The URL to capture (http:...|file:...|...)
 TARGET=${2}                     # The target file (.png|pdf|ps|svg|jpeg|...)
@@ -44,7 +44,7 @@ TIMESTAMP="$(date +%F\ %H:%M:%S)"
 
 function die()
 {
-    if [[ ! -z ${1} ]];
+    if [[ ! -z $1 ]];
     then
         printf "%s: %s\n\n" "$PROGNAME" "$1" 1>&2
     fi
@@ -96,21 +96,21 @@ then
     TARGET="${TARGET}.${EXTENSION}"
 fi
 
-if [[ -e ${TARGET} ]]                       # does TARGET exist?
+if [[ -e $TARGET ]]                       # does TARGET exist?
 then
     die "Output file already exists!"
 fi
 
 echo "Saving to \"$TARGET\" .."
 printf "Running cutycapt.. "
-cutycapt ${FLAGS} --url="${URL}" --out="${TARGET}"
+cutycapt $FLAGS --url="$URL" --out="$TARGET"
 
-if [[ -e "${TARGET}" ]]
+if [[ -e $TARGET ]]
 then
     printf "Adding label.."
     temp_name="${TARGET%.*}_labeled.${EXTENSION}"
 
-    convert "${TARGET}" -background White \
+    convert "$TARGET" -background White \
     label:"${TIMESTAMP}: \'${URL}\'  .. generated by ${PROGNAME}." \
     -gravity Center -append \
     "$temp_name"
@@ -118,9 +118,9 @@ else
     printf "Adding label FAILED!"
 fi
 
-if [[ -e ${temp_name} ]]
+if [[ -e $temp_name ]]
 then
-    mv "${temp_name}" "${TARGET}"
+    mv "$temp_name" "$TARGET"
 fi
 
 printf " DONE!\n"
